# fly.toml app configuration file generated for librechat-orbit on 2026-05-11T08:39:35Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'librechat-orbit'
primary_region = 'sjc'

[build]
  dockerfile = 'Dockerfile.fly'

[env]
  ALLOW_EMAIL_LOGIN = 'true'
  ALLOW_REGISTRATION = 'true'
  HOST = '0.0.0.0'
  NODE_ENV = 'production'
  PORT = '3080'
  SEARCH = 'false'

[http_service]
  internal_port = 3080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1gb'
