app = "librechat-orbit"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile.fly"

[env]
  HOST = "0.0.0.0"
  PORT = "3080"
  NODE_ENV = "production"
  ALLOW_REGISTRATION = "false"
  ALLOW_EMAIL_LOGIN = "true"
  SEARCH = "false"

[http_service]
  internal_port = 3080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = "shared-cpu-1x"
  memory = "1gb"
